services:
  mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - database-volume:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./docker/${ENV}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/api:/apps/api
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/${ENV}/php/Dockerfile
    volumes:
      - ./apps/api:/apps/api
    restart: on-failure
    env_file:
      - .env
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8&charset=utf8mb4"
    user: ${LOCAL_USER}

volumes:
  database-volume:
