@startuml

actor Customer
participant BileMo
participant "Database" as DB

Customer -> BileMo : GET /users/{userId}
activate BileMo
BileMo -> DB : SELECT * FROM customer_users cu \nINNER JOIN customers c \nON cu.customer_id = c.id \nWHERE c.id = ? AND cu.user_id = ?
activate DB
DB -> BileMo : Customer user row
deactivate DB
BileMo -> Customer : [200 Response status code] Json customer user details
deactivate BileMo


@enduml
