league_oauth2_server:
    client:
        classname: App\Entity\Customer
    authorization_server:
        enable_client_credentials_grant: true
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        access_token_ttl: "P1D"
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available: ['email']
        default: ['email']
    persistence:
        doctrine: null

when@test:
    league_oauth2_server:
        persistence:
            doctrine: null
